@startuml runner

' config includes
!include ../config/macros.iuml
!include ../config/styles.iuml

' diagram includes
!include ../GameEngine/packages/game.puml
!include ../GameEngine/packages/io.puml

' class diagram (https://plantuml.com/class-diagram)
$package(runner) {
    class GameRunner {
        {static} - GAME_IO_FACTORY: GameIOFactory {readOnly}
        {static} - PLAYER_FACTORY: PlayerFactory {readOnly}
        --
        {static} + main(): void
        {static} - createGameIOFactory(): GameIOFactory
        {static} - createPlayerFactory(): PlayerFactory
    }
    GameRunner --> engine.io.GameIOFactory : {static} - GAME_IO_FACTORY: GameIOFactory {readOnly}
    GameRunner --> engine.game.player.PlayerFactory : {static} - PLAYER_FACTORY: PlayerFactory {readOnly}
}

@enduml
