@startuml classes

' styling options
!include %dirpath()/styles/class.iuml

' diagram imports
!include %dirpath()/subclasses/GameEngine.puml
!include %dirpath()/subclasses/GameCommunication.puml
!include %dirpath()/subclasses/GamePlainText.puml
!include %dirpath()/subclasses/GameConsole.puml
!include %dirpath()/subclasses/GameBot.puml
!include %dirpath()/subclasses/GameRunner.puml

@enduml
