@startuml se

' config includes
!include config/styles.iuml

' component diagram (https://plantuml.com/component-diagram)
[GameEngine] as engine
[GameCommunication] as communication
[GamePlainText] as plaintext
[GameConsole] as console
[GameBot] as bot
[GameRunner] as runner

communication --> engine

plaintext --> communication
plaintext --> engine

console --> communication
console --> engine

bot --> engine

runner --> engine
runner --> communication
runner --> plaintext
runner --> console
runner --> bot

@enduml
